# -*- coding: utf-8 -*-
"""project_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_5CEegzjktdhLU2HwKZkuK4TMn38MG8
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score

#Load and understand the dataset
df = pd.read_csv('Iris.csv.xls')
df.info()
df.isnull().sum()
df.head()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
df.head()
df['Species'].unique()

x = df.drop(['Id','Species'],axis=1)
y = df['Species']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
x = scaler.fit_transform(x)
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))